[package]
name = "catfish"
version = "0.1.0"
edition = "2021"
authors = ["Shrikrishna Bhat"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.16"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
rand = "0.8"
