[package]
name = "email_system"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "email_system"

[dependencies]
actix-web = "4.8.0"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"

[dev-dependencies]
reqwest = "0.12.5"